version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=general-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=express_sequelize_example
    ports:
      - target: 3306
        published: 3306
        mode: host