name: lint check
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: cp .env.example .env
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn tsc
      - run: yarn build